// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjnC4OrLAt6iBfC3TzJ2-NSi1SRsm-_b0',
    appId: '1:272261296841:ios:cea1d0a03ea51541865318',
    messagingSenderId: '272261296841',
    projectId: 'flutterappproject-a8808',
    databaseURL: 'https://flutterappproject-a8808-default-rtdb.firebaseio.com',
    storageBucket: 'flutterappproject-a8808.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9ItpzRnPJ9PDzpTwuXjlYGB9SQ-iIgY0',
    appId: '1:272261296841:web:bc1634a08eb18058865318',
    messagingSenderId: '272261296841',
    projectId: 'flutterappproject-a8808',
    authDomain: 'flutterappproject-a8808.firebaseapp.com',
    databaseURL: 'https://flutterappproject-a8808-default-rtdb.firebaseio.com',
    storageBucket: 'flutterappproject-a8808.firebasestorage.app',
    measurementId: 'G-YE4M4EXRLS',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9ItpzRnPJ9PDzpTwuXjlYGB9SQ-iIgY0',
    appId: '1:272261296841:web:bc1634a08eb18058865318',
    messagingSenderId: '272261296841',
    projectId: 'flutterappproject-a8808',
    authDomain: 'flutterappproject-a8808.firebaseapp.com',
    databaseURL: 'https://flutterappproject-a8808-default-rtdb.firebaseio.com',
    storageBucket: 'flutterappproject-a8808.firebasestorage.app',
    measurementId: 'G-YE4M4EXRLS',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjnC4OrLAt6iBfC3TzJ2-NSi1SRsm-_b0',
    appId: '1:272261296841:ios:cea1d0a03ea51541865318',
    messagingSenderId: '272261296841',
    projectId: 'flutterappproject-a8808',
    databaseURL: 'https://flutterappproject-a8808-default-rtdb.firebaseio.com',
    storageBucket: 'flutterappproject-a8808.firebasestorage.app',
    iosBundleId: 'com.example.firstApp',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3U0e5NQ8P432BPbj9mcsR7us2Eue1D3s',
    appId: '1:272261296841:android:e95f46b4cd30786a865318',
    messagingSenderId: '272261296841',
    projectId: 'flutterappproject-a8808',
    databaseURL: 'https://flutterappproject-a8808-default-rtdb.firebaseio.com',
    storageBucket: 'flutterappproject-a8808.firebasestorage.app',
  );

}